# __Natural Language Processing__

In [1]:
import pandas as pd
import numpy as np
import nltk

In [33]:
import re
import string

In [2]:
df = pd.read_csv("movie_reviews.csv", delimiter='\t')
df.head()

                   review sentiment
0  This movie was amazing  Positive
1     I loved every scene  Positive
2        Fantastic acting  Positive
3         Best movie ever  Positive
4         Wonderful story  Positive

In [18]:
df.duplicated().sum()

np.int64(0)

In [4]:
df['sentiment'].value_counts()

sentiment
Positive    10
Negative    10
Name: count, dtype: int64

In [7]:
df['review'].values

array(['This movie was amazing', 'I loved every scene',
       'Fantastic acting', 'Best movie ever', 'Wonderful story',
       'Excellent direction', 'Superb cinematography',
       'Highly recommended', 'Brilliant screenplay',
       'I enjoyed the movie', 'Worst movie ever', 'I hated this film',
       'Terrible acting', 'Waste of time', 'Very boring', 'Bad storyline',
       'Poor direction', 'Not recommended', 'Horrible experience',
       'Disappointing movie'], dtype=object)

In [34]:
def clean_text(tex):
    tex = tex.lower()
    tex = re.sub(r'https?://\S+', '', tex)
    tex = tex.translate(str.maketrans('', '', string.punctuation))
    tex = tex.encode('ascii', 'ignore').decode('ascii')
    tex = re.sub(r'\s+', ' ', tex).strip()
    return tex

In [35]:
df["clean_review"] = df["review"].apply(clean_text)

In [36]:
df[['review', 'clean_review']].head()

                   review            clean_review
0  This movie was amazing  this movie was amazing
1     I loved every scene     i loved every scene
2        Fantastic acting        fantastic acting
3         Best movie ever         best movie ever
4         Wonderful story         wonderful story

In [39]:
df['token'] = df['clean_review'].apply(word_tokenize)

In [41]:
df['token_count'] = df['token'].apply(len)

In [42]:
df.head()

,review,sentiment,token,clean_review,token_count
0,This movie was amazing,Positive,"[this, movie, was, amazing]",this movie was amazing,4
1,I loved every scene,Positive,"[i, loved, every, scene]",i loved every scene,4
2,Fantastic acting,Positive,"[fantastic, acting]",fantastic acting,2
3,Best movie ever,Positive,"[best, movie, ever]",best movie ever,3
4,Wonderful story,Positive,"[wonderful, story]",wonderful story,2

In [40]:
df['token']

0     [this, movie, was, amazing]
1        [i, loved, every, scene]
2             [fantastic, acting]
3             [best, movie, ever]
4              [wonderful, story]
5          [excellent, direction]
6        [superb, cinematography]
7           [highly, recommended]
8         [brilliant, screenplay]
9        [i, enjoyed, the, movie]
10           [worst, movie, ever]
11         [i, hated, this, film]
12             [terrible, acting]
13              [waste, of, time]
14                 [very, boring]
15               [bad, storyline]
16              [poor, direction]
17             [not, recommended]
18         [horrible, experience]
19         [disappointing, movie]
Name: token, dtype: object

In [47]:
df["filtered_tokens"] = df["token"].apply(
    lambda token: [word for word in token if word not in stop_words]
)

In [48]:
df.head()

,review,sentiment,token,clean_review,token_count,filtered_tokens
0,This movie was amazing,Positive,"[this, movie, was, amazing]",this movie was amazing,4,"[movie, amazing]"
1,I loved every scene,Positive,"[i, loved, every, scene]",i loved every scene,4,"[loved, every, scene]"
2,Fantastic acting,Positive,"[fantastic, acting]",fantastic acting,2,"[fantastic, acting]"
3,Best movie ever,Positive,"[best, movie, ever]",best movie ever,3,"[best, movie, ever]"
4,Wonderful story,Positive,"[wonderful, story]",wonderful story,2,"[wonderful, story]"

In [49]:
df["filtered_count"] = df["filtered_tokens"].apply(len)

df[["token_count", "filtered_count"]].head()

   token_count  filtered_count
0            4               2
1            4               3
2            2               2
3            3               3
4            2               2

In [50]:
custom_stop_words = set(stopwords.words("english"))

custom_stop_words.discard("not")
custom_stop_words.discard("no")
custom_stop_words.discard("never")

In [51]:
df['filtered_tokens'] = df['token'].apply(
    lambda token: [word for word in token if word not in custom_stop_words]
)

In [52]:
df.head()

,review,sentiment,token,clean_review,token_count,filtered_tokens,filtered_count
0,This movie was amazing,Positive,"[this, movie, was, amazing]",this movie was amazing,4,"[movie, amazing]",2
1,I loved every scene,Positive,"[i, loved, every, scene]",i loved every scene,4,"[loved, every, scene]",3
2,Fantastic acting,Positive,"[fantastic, acting]",fantastic acting,2,"[fantastic, acting]",2
3,Best movie ever,Positive,"[best, movie, ever]",best movie ever,3,"[best, movie, ever]",3
4,Wonderful story,Positive,"[wonderful, story]",wonderful story,2,"[wonderful, story]",2

In [55]:
stemmer = PorterStemmer()
lemitizer = WordNetLemmatizer()

In [56]:
df['stemmed_token'] = df['filtered_tokens'].apply(
    lambda token: [stemmer.stem(word) for word in token]
)

In [58]:
df[['filtered_tokens', 'stemmed_token']].head()

         filtered_tokens         stemmed_token
0       [movie, amazing]          [movi, amaz]
1  [loved, every, scene]  [love, everi, scene]
2    [fantastic, acting]        [fantast, act]
3    [best, movie, ever]    [best, movi, ever]
4     [wonderful, story]       [wonder, stori]

In [62]:
df['lematized_token'] = df['filtered_tokens'].apply(
    lambda token: [lemitizer.lemmatize(word, pos='v') for word in token]
)

df[['filtered_tokens','lematized_token']].head()

         filtered_tokens       lematized_token
0       [movie, amazing]        [movie, amaze]
1  [loved, every, scene]  [love, every, scene]
2    [fantastic, acting]      [fantastic, act]
3    [best, movie, ever]   [best, movie, ever]
4     [wonderful, story]    [wonderful, story]

In [67]:
df['processed_review'] = df['lematized_token'].apply(
    lambda token: " ".join(token)
)
df[['review','processed_review']].head()

                   review  processed_review
0  This movie was amazing       movie amaze
1     I loved every scene  love every scene
2        Fantastic acting     fantastic act
3         Best movie ever   best movie ever
4         Wonderful story   wonderful story

In [85]:
X1 = cv.fit_transform(df['processed_review'])

In [86]:
print(X1.shape)

(20, 34)

In [72]:
print(cv.get_feature_names_out())

['act' 'amaze' 'bad' 'best' 'bore' 'brilliant' 'cinematography'
 'direction' 'disappoint' 'enjoy' 'ever' 'every' 'excellent' 'experience'
 'fantastic' 'film' 'hat' 'highly' 'horrible' 'love' 'movie' 'not' 'poor'
 'recommend' 'scene' 'screenplay' 'story' 'storyline' 'superb' 'terrible'
 'time' 'waste' 'wonderful' 'worst']

In [87]:
bow_df = pd.DataFrame(
    X1.toarray(),
    columns=cv.get_feature_names_out()
)

bow_df.head()

,act,amaze,bad,best,bore,brilliant,cinematography,direction,disappoint,enjoy,...,scene,screenplay,story,storyline,superb,terrible,time,waste,wonderful,worst
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [88]:
X2 = tfidf.fit_transform(df['processed_review'])

In [89]:
print(X2.shape)

(20, 34)

In [83]:
print(tfidf.get_feature_names_out())

['act' 'amaze' 'bad' 'best' 'bore' 'brilliant' 'cinematography'
 'direction' 'disappoint' 'enjoy' 'ever' 'every' 'excellent' 'experience'
 'fantastic' 'film' 'hat' 'highly' 'horrible' 'love' 'movie' 'not' 'poor'
 'recommend' 'scene' 'screenplay' 'story' 'storyline' 'superb' 'terrible'
 'time' 'waste' 'wonderful' 'worst']

In [90]:
tfidf_df = pd.DataFrame(
    X2.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

,act,amaze,bad,best,bore,brilliant,cinematography,direction,disappoint,enjoy,...,scene,screenplay,story,storyline,superb,terrible,time,waste,wonderful,worst
0,0.000000,0.829928,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.57735,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.660211,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.000000,0.000000,0.0,0.670476,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.707107,0.0,0.0,0.0,0.0,0.0,0.707107,0.0

In [91]:
Y = df['sentiment']

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
X1_train, X1_test, Y_train, Y_test = train_test_split(X1, Y, test_size=0.2, random_state=42)

In [94]:
X2_train, X2_test, Y_train, Y_test = train_test_split(X2, Y, test_size=0.2, random_state=42)

In [119]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

lr_model = LogisticRegression(random_state=42)
svm_model = LinearSVC(random_state=42)
model = MultinomialNB()

In [103]:
model.fit(X1_train,Y_train)

MultinomialNB()

In [145]:
model.fit(X2_train,Y_train)

MultinomialNB()

In [146]:
joblib.dump(model, "sentiment_model.pkl")

['sentiment_model.pkl']

In [107]:
y_predict1 = model.predict(X1_test)

In [108]:
y_predict2 = model.predict(X2_test)

In [ ]:
print(y_predict1) # BoW

['Negative' 'Positive' 'Negative' 'Negative']

In [116]:
print(y_predict2) # TF-IDF

['Negative' 'Positive' 'Negative' 'Negative']

In [114]:
Y_test

0     Positive
17    Negative
15    Negative
1     Positive
Name: sentiment, dtype: object

In [126]:
accuracy_nb = accuracy_score(Y_test, y_predict)

In [127]:
accuracy_nb

0.25

In [120]:
# Logistic Regression
lr_model.fit(X2_train,Y_train)

LogisticRegression(random_state=42)

In [122]:
lr_pred = lr_model.predict(X1_test)

In [121]:
# SVM 
svm_model.fit(X1_train, Y_train)

LinearSVC(random_state=42)

In [123]:
svm_pred = svm_model.predict(X1_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [133]:
accuracy_lr = accuracy_score(Y_test, lr_pred)
print(accuracy_lr)

0.25

In [132]:
accuracy_svm = accuracy_score(Y_test, svm_pred)
print(accuracy_svm)

0.25

In [137]:
import joblib

In [138]:
joblib.dump(model, "sentiment_model.pkl")

['sentiment_model.pkl']

In [139]:
joblib.dump(tfidf, "tfidf_vectors.pkl")

['tfidf_vectors.pkl']

In [140]:
joblib.dump(cv, "BoW_vectors.pkl")

['BoW_vectors.pkl']

In [141]:
loaded_model = joblib.load("sentiment_model.pkl")

In [74]:
review = df.loc[0, 'processed_review']
print(review)

movie amaze

In [75]:
words = review.split()
print(words)

['movie', 'amaze']

In [76]:
from collections import Counter

counter = Counter(words)
print(counter)

Counter({'movie': 1, 'amaze': 1})

In [78]:
total = len(words)

tf = {}

for word, count in counter.items():
    tf[word] = count / total

print(tf)

{'movie': 0.5, 'amaze': 0.5}

## __Tokenization__

In [6]:
text = "Text becomes numbers. Specifically, text becomes vectors — lists of numbers — positioned in space so that things with similar meaning end up physically close together in that space. Dog and puppy land near each other. Dog and stock market land far apart. That's it. That single idea — meaning as geometry — is the load-bearing concept behind search engines, chatbots, recommendation systems, spam filters, and RAG pipelines. Everyone teaches this last, buried under weeks of theory. You're learning it first, in the next ten minutes, because once it clicks, everything else is just okay, and what do we do with the vectors."

In [7]:
text

"Text becomes numbers. Specifically, text becomes vectors — lists of numbers — positioned in space so that things with similar meaning end up physically close together in that space. Dog and puppy land near each other. Dog and stock market land far apart. That's it. That single idea — meaning as geometry — is the load-bearing concept behind search engines, chatbots, recommendation systems, spam filters, and RAG pipelines. Everyone teaches this last, buried under weeks of theory. You're learning it first, in the next ten minutes, because once it clicks, everything else is just okay, and what do we do with the vectors."

In [3]:
from nltk.tokenize  import  word_tokenize, sent_tokenize

In [14]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RUPESH\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\RUPESH\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [7]:
word = word_tokenize(text)

In [8]:
word

['Text',
 'becomes',
 'numbers',
 '.',
 'Specifically',
 ',',
 'text',
 'becomes',
 'vectors',
 '—',
 'lists',
 'of',
 'numbers',
 '—',
 'positioned',
 'in',
 'space',
 'so',
 'that',
 'things',
 'with',
 'similar',
 'meaning',
 'end',
 'up',
 'physically',
 'close',
 'together',
 'in',
 'that',
 'space',
 '.',
 'Dog',
 'and',
 'puppy',
 'land',
 'near',
 'each',
 'other',
 '.',
 'Dog',
 'and',
 'stock',
 'market',
 'land',
 'far',
 'apart',
 '.',
 'That',
 "'s",
 'it',
 '.',
 'That',
 'single',
 'idea',
 '—',
 'meaning',
 'as',
 'geometry',
 '—',
 'is',
 'the',
 'load-bearing',
 'concept',
 'behind',
 'search',
 'engines',
 ',',
 'chatbots',
 ',',
 'recommendation',
 'systems',
 ',',
 'spam',
 'filters',
 ',',
 'and',
 'RAG',
 'pipelines',
 '.',
 'Everyone',
 'teaches',
 'this',
 'last',
 ',',
 'buried',
 'under',
 'weeks',
 'of',
 'theory',
 '.',
 'You',
 "'re",
 'learning',
 'it',
 'first',
 ',',
 'in',
 'the',
 'next',
 'ten',
 'minutes',
 ',',
 'because',
 'once',
 'it',
 'clicks',
 ',',
 'everything',
 'else',
 'is',
 'just',
 'okay',
 ',',
 'and',
 'what',
 'do',
 'we',
 'do',
 'with',
 'the',
 'vectors',
 '.']

In [9]:
sentence = sent_tokenize(text)

In [19]:
sentence

['Text becomes numbers.',
 'Specifically, text becomes vectors — lists of numbers — positioned in space so that things with similar meaning end up physically close together in that space.',
 'Dog and puppy land near each other.',
 'Dog and stock market land far apart.',
 "That's it.",
 'That single idea — meaning as geometry — is the load-bearing concept behind search engines, chatbots, recommendation systems, spam filters, and RAG pipelines.',
 'Everyone teaches this last, buried under weeks of theory.',
 "You're learning it first, in the next ten minutes, because once it clicks, everything else is just okay, and what do we do with the vectors."]

## __Stop Words Removing__

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RUPESH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [43]:
from nltk.corpus import stopwords
from string import punctuation

In [44]:
stop = stopwords.words('english')

In [ ]:
list(punctuation)

In [24]:
stop_words = list(punctuation) + stop

In [25]:
for i in word:
    if i not in stop_words:
        print(i)

Text
becomes
numbers
Specifically
text
becomes
vectors
—
lists
numbers
—
positioned
space
things
similar
meaning
end
physically
close
together
space
Dog
puppy
land
near
Dog
stock
market
land
far
apart
That
's
That
single
idea
—
meaning
geometry
—
load-bearing
concept
behind
search
engines
chatbots
recommendation
systems
spam
filters
RAG
pipelines
Everyone
teaches
last
buried
weeks
theory
You
're
learning
first
next
ten
minutes
clicks
everything
else
okay
vectors

## __Stemming & Lemitization__

In [12]:
from nltk.stem import LancasterStemmer, RegexpStemmer, PorterStemmer, SnowballStemmer

l = LancasterStemmer()
r = RegexpStemmer('ing')
p = PorterStemmer()
s = SnowballStemmer('english')

In [53]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\RUPESH\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [13]:
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [26]:
wl.lemmatize("Orange")

'Orange'

## __N-Grams__

In [14]:
from nltk.collocations import BigramCollocationFinder, TrigramCollocationFinder, ngrams

In [15]:
b = BigramCollocationFinder.from_words(word)
t = TrigramCollocationFinder.from_words(word)
n = ngrams(word, 1)

In [ ]:
b.ngram_fd.keys()

dict_keys([('Text', 'becomes'), ('becomes', 'numbers'), ('numbers', '.'), ('.', 'Specifically'), ('Specifically', ','), (',', 'text'), ('text', 'becomes'), ('becomes', 'vectors'), ('vectors', '—'), ('—', 'lists'), ('lists', 'of'), ('of', 'numbers'), ('numbers', '—'), ('—', 'positioned'), ('positioned', 'in'), ('in', 'space'), ('space', 'so'), ('so', 'that'), ('that', 'things'), ('things', 'with'), ('with', 'similar'), ('similar', 'meaning'), ('meaning', 'end'), ('end', 'up'), ('up', 'physically'), ('physically', 'close'), ('close', 'together'), ('together', 'in'), ('in', 'that'), ('that', 'space'), ('space', '.'), ('.', 'Dog'), ('Dog', 'and'), ('and', 'puppy'), ('puppy', 'land'), ('land', 'near'), ('near', 'each'), ('each', 'other'), ('other', '.'), ('and', 'stock'), ('stock', 'market'), ('market', 'land'), ('land', 'far'), ('far', 'apart'), ('apart', '.'), ('.', 'That'), ('That', "'s"), ("'s", 'it'), ('it', '.'), ('That', 'single'), ('single', 'idea'), ('idea', '—'), ('—', 'meaning'), ('meaning', 'as'), ('as', 'geometry'), ('geometry', '—'), ('—', 'is'), ('is', 'the'), ('the', 'load-bearing'), ('load-bearing', 'concept'), ('concept', 'behind'), ('behind', 'search'), ('search', 'engines'), ('engines', ','), (',', 'chatbots'), ('chatbots', ','), (',', 'recommendation'), ('recommendation', 'systems'), ('systems', ','), (',', 'spam'), ('spam', 'filters'), ('filters', ','), (',', 'and'), ('and', 'RAG'), ('RAG', 'pipelines'), ('pipelines', '.'), ('.', 'Everyone'), ('Everyone', 'teaches'), ('teaches', 'this'), ('this', 'last'), ('last', ','), (',', 'buried'), ('buried', 'under'), ('under', 'weeks'), ('weeks', 'of'), ('of', 'theory'), ('theory', '.'), ('.', 'You'), ('You', "'re"), ("'re", 'learning'), ('learning', 'it'), ('it', 'first'), ('first', ','), (',', 'in'), ('in', 'the'), ('the', 'next'), ('next', 'ten'), ('ten', 'minutes'), ('minutes', ','), (',', 'because'), ('because', 'once'), ('once', 'it'), ('it', 'clicks'), ('clicks', ','), (',', 'everything'), ('everything', 'else'), ('else', 'is'), ('is', 'just'), ('just', 'okay'), ('okay', ','), ('and', 'what'), ('what', 'do'), ('do', 'we'), ('we', 'do'), ('do', 'with'), ('with', 'the'), ('the', 'vectors'), ('vectors', '.')])

In [30]:
t.ngram_fd

FreqDist({('.', 'Dog', 'and'): 2, ('Text', 'becomes', 'numbers'): 1, ('becomes', 'numbers', '.'): 1, ('numbers', '.', 'Specifically'): 1, ('.', 'Specifically', ','): 1, ('Specifically', ',', 'text'): 1, (',', 'text', 'becomes'): 1, ('text', 'becomes', 'vectors'): 1, ('becomes', 'vectors', '—'): 1, ('vectors', '—', 'lists'): 1, ...})

In [31]:
for i in n:
    print(i)

('Text',)
('becomes',)
('numbers',)
('.',)
('Specifically',)
(',',)
('text',)
('becomes',)
('vectors',)
('—',)
('lists',)
('of',)
('numbers',)
('—',)
('positioned',)
('in',)
('space',)
('so',)
('that',)
('things',)
('with',)
('similar',)
('meaning',)
('end',)
('up',)
('physically',)
('close',)
('together',)
('in',)
('that',)
('space',)
('.',)
('Dog',)
('and',)
('puppy',)
('land',)
('near',)
('each',)
('other',)
('.',)
('Dog',)
('and',)
('stock',)
('market',)
('land',)
('far',)
('apart',)
('.',)
('That',)
("'s",)
('it',)
('.',)
('That',)
('single',)
('idea',)
('—',)
('meaning',)
('as',)
('geometry',)
('—',)
('is',)
('the',)
('load-bearing',)
('concept',)
('behind',)
('search',)
('engines',)
(',',)
('chatbots',)
(',',)
('recommendation',)
('systems',)
(',',)
('spam',)
('filters',)
(',',)
('and',)
('RAG',)
('pipelines',)
('.',)
('Everyone',)
('teaches',)
('this',)
('last',)
(',',)
('buried',)
('under',)
('weeks',)
('of',)
('theory',)
('.',)
('You',)
("'re",)
('learning',)
('it',)
('first',)
(',',)
('in',)
('the',)
('next',)
('ten',)
('minutes',)
(',',)
('because',)
('once',)
('it',)
('clicks',)
(',',)
('everything',)
('else',)
('is',)
('just',)
('okay',)
(',',)
('and',)
('what',)
('do',)
('we',)
('do',)
('with',)
('the',)
('vectors',)
('.',)

## __Count Vectorization__

In [68]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [64]:
vectors = cv.fit_transform(df['review']).toarray()

In [65]:
vectors

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
cv.vocabulary_

{'this': 32,
 'movie': 20,
 'was': 35,
 'amazing': 1,
 'loved': 19,
 'every': 11,
 'scene': 25,
 'fantastic': 14,
 'acting': 0,
 'best': 3,
 'ever': 10,
 'wonderful': 37,
 'story': 27,
 'excellent': 12,
 'direction': 7,
 'superb': 29,
 'cinematography': 6,
 'highly': 17,
 'recommended': 24,
 'brilliant': 5,
 'screenplay': 26,
 'enjoyed': 9,
 'the': 31,
 'worst': 38,
 'hated': 16,
 'film': 15,
 'terrible': 30,
 'waste': 36,
 'of': 22,
 'time': 33,
 'very': 34,
 'boring': 4,
 'bad': 2,
 'storyline': 28,
 'poor': 23,
 'not': 21,
 'horrible': 18,
 'experience': 13,
 'disappointing': 8}