# __Part 2__ Data Preprocessing

## __Task 5__

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Tatanic.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [3]:
print(df.shape)
print(df.columns)

(418, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [4]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

## __Task 6__

In [7]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [8]:
df['age'] = df['age'].fillna(df['age'].median())

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop(columns=['cabin'])

In [11]:
df.isnull().sum()

passengerid    0
survived       0
pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           1
embarked       0
dtype: int64

In [12]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

## __Task 7__ --> Feature Preparation

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [14]:
df['sex'] = le.fit_transform(df['sex'])
df['name'] = le.fit_transform(df['name'])

In [15]:
df = pd.get_dummies(df, columns=['embarked'])

In [16]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked_C,embarked_Q,embarked_S
0,892,0,3,206,1,34.5,0,0,330911,7.8292,False,True,False
1,893,1,3,403,0,47.0,1,0,363272,7.0000,False,False,True
2,894,0,2,269,1,62.0,0,0,240276,9.6875,False,True,False
3,895,0,3,408,1,27.0,0,0,315154,8.6625,False,False,True
4,896,1,3,178,0,22.0,1,1,3101298,12.2875,False,False,True

In [17]:
df['embarked_C'] = le.fit_transform(df['embarked_C'])
df['embarked_Q'] = le.fit_transform(df['embarked_Q'])
df['embarked_S'] = le.fit_transform(df['embarked_S'])

In [18]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked_C,embarked_Q,embarked_S
0,892,0,3,206,1,34.5,0,0,330911,7.8292,0,1,0
1,893,1,3,403,0,47.0,1,0,363272,7.0000,0,0,1
2,894,0,2,269,1,62.0,0,0,240276,9.6875,0,1,0
3,895,0,3,408,1,27.0,0,0,315154,8.6625,0,0,1
4,896,1,3,178,0,22.0,1,1,3101298,12.2875,0,0,1

## Seperate data Input & Output

In [19]:
X = df.drop(columns=['survived','passengerid'])
Y = df['survived']

In [20]:
X

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked_C,embarked_Q,embarked_S
0,3,206,1,34.5,0,0,330911,7.8292,0,1,0
1,3,403,0,47.0,1,0,363272,7.0000,0,0,1
2,2,269,1,62.0,0,0,240276,9.6875,0,1,0
3,3,408,1,27.0,0,0,315154,8.6625,0,0,1
4,3,178,0,22.0,1,1,3101298,12.2875,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
413,3,353,1,27.0,0,0,A.5. 3236,8.0500,0,0,1
414,1,283,0,39.0,0,0,PC 17758,108.9000,1,0,0
415,3,332,1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,0,0,1
416,3,384,1,27.0,0,0,359309,8.0500,0,0,1
417,3,302,1,27.0,1,1,2668,22.3583,1,0,0

In [21]:
Y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: survived, Length: 418, dtype: int64