In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("January_23.csv")
df.head()

,order_id,orderDate,customer_id,Resturant_ID,Fooditem,quantity,deliver_status,payment_method
0,254001,01-01-2023,30,211,2142,4,Delivered,COD
1,254002,01-01-2023,25,214,2152,7,Delivered,COD
2,254003,01-01-2023,28,212,2145,2,Delivered,UPI
3,254004,01-01-2023,4,213,2149,2,Delivered,UPI
4,254005,01-01-2023,30,211,2141,4,Cancelled,UPI

In [7]:
df.tail()

,order_id,orderDate,customer_id,Resturant_ID,Fooditem,quantity,deliver_status,payment_method
621,254622,31-01-2023,13,214,2154,6,Delivered,COD
622,254623,31-01-2023,13,213,2150,6,Delivered,UPI
623,254624,31-01-2023,4,217,2165,9,Delivered,COD
624,254625,31-01-2023,25,212,2145,10,Delivered,Card
625,254626,31-01-2023,28,211,2144,7,Delivered,UPI

In [3]:
df.describe()

            order_id  customer_id  Resturant_ID     Fooditem    quantity
count     626.000000   626.000000    626.000000   626.000000  626.000000
mean   254313.500000    14.920128    213.071885  2149.993610    5.437700
std       180.854914     9.149427      1.970082     7.575537    2.807439
min    254001.000000     1.000000    211.000000  2141.000000    1.000000
25%    254157.250000     5.000000    212.000000  2145.000000    3.000000
50%    254313.500000    15.000000    212.000000  2147.000000    5.000000
75%    254469.750000    25.000000    214.000000  2154.000000    8.000000
max    254626.000000    30.000000    217.000000  2167.000000   10.000000

In [6]:
df.isnull().sum()

order_id          0
orderDate         0
customer_id       0
Resturant_ID      0
Fooditem          0
quantity          0
deliver_status    0
payment_method    0
dtype: int64

In [7]:
df.sample(5)

,order_id,orderDate,customer_id,Resturant_ID,Fooditem,quantity,deliver_status,payment_method
525,254526,29-01-2023,25,217,2165,2,Delivered,Card
462,254463,25-01-2023,19,216,2160,9,Cancelled,COD
232,254233,15-01-2023,25,213,2149,4,Delivered,UPI
527,254528,29-01-2023,15,216,2160,9,Delivered,COD
592,254593,31-01-2023,4,212,2145,1,Delivered,Card